# docker-compose.yml
version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: microblog-db
    environment:
      POSTGRES_DB: microblog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"  # puerto principal
    environment:
      - SERVICES=sqs
      - EDGE_PORT=4566
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      
volumes:
  pgdata:
